version: '3'
services:
  browser:
    # See inside via VNC with the "debug" version
    image: selenium/standalone-chrome
    ports:
      - "5900:5900" #for VNC access
      - "4444:4444" #for webdriver access

  ruby:
    build: .
    environment:
      ENV: DEV
      URL: 'https://inm-test-app.herokuapp.com'
    volumes:
      - .:/app
    depends_on:
      - browser